
POST  http://localhost:8080/api/v1/login
content-type: application/json

{
    "key": "new@gmail.com",
    "password": "123"
}

###
DELETE http://localhost:8080/user/delete-user/11221
content-type: application/json

{
    "userName": "new@gmail.com",
    "password": "123"
}

###
POST http://localhost:8080/user/create
content-type: application/json

{
    "userName":" data.userName",
    "address": "data",
    "email":"new@gmail.com",
    "phone": "data",
    "sex": "data",
    "password": "123",
}
